services:
  wiremock:
    image: wiremock/wiremock:2.32.0
    container_name: wiremock
    volumes:
      - ./Wiremock:/home/wiremock
    ports:
      - 8080:8080
    healthcheck:
      test: curl --fail http://localhost:8080/api/health || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
  next-accelerator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: next-accelerator
    ports:
      - 3000:3000
    healthcheck:
      test: curl --fail http://localhost:3000/api/health || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    environment:
      - BACKEND_URL=${BACKEND_URL}
